v-01_f-01_add_task
Artem-spec/carsharing pull request #1
Opened 2021-09-22 16:37 UTC by Artem-spec

2021-09-23 19:30 UTC, EvgeniyaFilatova requested changes

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/BurgerMenu/BurgerMenu.js
> +export default function BurgerMenu(props) {
- [ ] Лучше деструктурировать объекты, так код будет более читаем. Если объект не очень большой, то можно это сделать прямо здесь, в параметрах функции, но лучше выносить это внутри функции вот так:
const {
setActive,
setLenguache,
language } = props;
И в коде уже использовать эти переменные без props.

- [ ] Еще лучше используй новые возможности JS, давай писать компоненты с помощью стрелочных функций, исправь везде по проекту

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/BurgerMenu/burgerMenu.scss
> +@media (max-width: 320px) {
- [ ] Приведи все разрешения под следующие требования (это взято из фигмы, со страницы Техническое задание). То есть стили для @media (max-width: 320px)  у тебя должны идти уже от 767px и так далее
![image](https://user-images.githubusercontent.com/90593835/134568299-cadfaaad-e487-4747-8e06-366aaef2fccd.png)

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/Menu/Menu.js
> +
- [ ] Удали этот файл, если он тебе не нужен

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/SelectCity/SelectCity.js
> +function mapStateToProps(state) {
- [ ] Попробуй использовать хуки редакса: useSelector и useReducer, почитай про них

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/Slider/Slider.js
> +        const circles = document.querySelectorAll('.slider__circle');
- [ ] Нет смысла использовать querySelector в Реакте, при отрисовке компонента у тебя и так определяется, какие классы навесить на элемент. При каждой смене состояния, реакт будет запускать перерендер компонента и классы будут меняться. Тебе нужно ниже (в return, где у тебя блок с кружками) сделать сравнение активного элемента и индекса определенного кружка и в зависимости от этого формировать className. Попробуй так сделать и не используй querySelector

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/Slider/slider.scss
> +.slider__image {
- [ ] У тебя плющатся картинки, в некоторых местах вообще едет верстка немного в слайдере. Вот, например, на iPad как выглядит.
![image](https://user-images.githubusercontent.com/90593835/134570851-c3ddd0eb-d0ec-47d9-bb44-fdc85a24d878.png)

На десктопе попробуй менять ширину блока со слайдером, а не оставлять его статичным, чтобы картинка всегда была одного размера и не плющилась
![image](https://user-images.githubusercontent.com/90593835/134571130-bec24dc8-90f0-4b63-b556-c51d03a14513.png)

2021-09-23 19:30 UTC, EvgeniyaFilatova commented on src/components/StartPage/BurgerMenu/burgerMenu.scss
> +.burger {
- [ ] На десктопе появляется полоса между меню и контентом основным, не хватает ширины меню
![image](https://user-images.githubusercontent.com/90593835/134571576-9379f117-3a5d-41d5-9ad7-b685c80b513a.png)

2021-09-24 13:54 UTC, Artem-spec commented on src/App.js
> +  let location = useLocation();
Исправлено

2021-09-24 13:55 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/BurgerList/burgerList.scss
> +$color-green: #0ec261;
Исправлено

2021-09-25 13:33 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/BurgerMenu.js
> +import './burgerMenu.scss';
Исправлено

2021-09-25 13:34 UTC, Artem-spec commented on src/App.js
> +    <Suspense fallback="loading">
Исправлено

2021-09-25 14:07 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/BurgerMenu.js
> +        <div className={props.active ? "burger active" : "burger"} onClick={() => { props.setActive(false); }}>
Исправлено

2021-09-25 15:48 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/BurgerMenu.js
> +export default function BurgerMenu(props) {
Исправлено

2021-09-25 16:28 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/burgerMenu.scss
> +@media (max-width: 320px) {
Исправлено

2021-09-25 17:13 UTC, Artem-spec commented on src/components/StartPage/Slider/slider.scss
> +.slider__image {
Исправлено

2021-09-25 17:27 UTC, Artem-spec commented on src/components/StartPage/BurgerMenu/burgerMenu.scss
> +.burger {
Исправлено.

2021-09-25 17:43 UTC, Artem-spec commented on src/components/StartPage/Slider/Slider.js
> +        const circles = document.querySelectorAll('.slider__circle');
Исправлено

2021-09-26 08:22 UTC, Artem-spec commented on src/components/StartPage/SelectCity/SelectCity.js
> +function mapStateToProps(state) {
Исправлено.
Использовал useSelector, для языка создал отдельный reducer redux без использования хука реакта useReducer (как я понял его можно просто передавать в качестве props, а язык будет использоваться на других страницах и передавать его в качестве пропса не получится).

2021-09-27 14:23 UTC, EvgeniyaFilatova requested changes

2021-09-27 14:23 UTC, EvgeniyaFilatova commented on src/components/StartPage/StartPage.js
> +                        <span href='#' className={classnames('start-page__language')} onClick={(e) => handleClickLinkLanguage(e)}>{language}</span>
- [ ] У тебя по проекту часто встречаются длинные строки кода, их очень неудобно читать, намного лучше разбивать атрибуты и пропсы по отдельным строкам. Попробуй подключить и настроить Prettier, с ним можно эти вещи делать автоматически.
Пример форматирования для данной строки:
![image](https://user-images.githubusercontent.com/90593835/134926105-081dc2b2-6db0-49c0-ba68-c7a71016522a.png)

2021-09-27 14:23 UTC, EvgeniyaFilatova commented on src/components/StartPage/StartPage.js
> +        changeLang
- [ ] Я тебя в прошлый раз сказала не про тут хук, попробуй тут использовать useDispatch, тогда connect не нужен будет

2021-09-27 15:26 UTC, Artem-spec commented on src/components/StartPage/SelectCity/SelectCity.js
> +            let value = event.target.value.toLowerCase().trim();
Исправлено

2021-09-27 15:41 UTC, Artem-spec commented on src/components/StartPage/StartPage.js
> +                        <span href='#' className={classnames('start-page__language')} onClick={(e) => handleClickLinkLanguage(e)}>{language}</span>
Исправлено

2021-09-27 17:30 UTC, Artem-spec commented on src/components/StartPage/StartPage.js
> +import Slider from "./Slider/Slider";
Исправлено

2021-09-27 17:30 UTC, Artem-spec commented on src/components/StartPage/StartPage.js
> +        console.log(language);
Исправлено

2021-09-28 05:56 UTC, EvgeniyaFilatova commented on src/components/StartPage/SelectCity/SelectCity.js
> +  function handleClick(e) {
Заменить на стрелочную функцию

2021-09-28 05:56 UTC, EvgeniyaFilatova commented on src/components/StartPage/SelectCity/SelectCity.js
> +  function handleChange(event) {
Заменить на стрелочную функцию

2021-09-28 05:56 UTC, EvgeniyaFilatova commented on src/components/StartPage/Slider/Slider.js
> +  const content = [
В массиве лучше не хранить разметку, а только непосредственно данные. Вся разметка должна быть в рендере компонента, то есть в return. Можешь сделать отдельный компонент SliderItem, например, и перенести туда всю разметку одного слайда и передавать туда данные через пропсы

2021-09-28 05:56 UTC, EvgeniyaFilatova commented on src/components/StartPage/Slider/Slider.js
> +  function handleClickInc() {
Здесь и ниже заменить на стрелочные

2021-09-28 14:23 UTC, merged