V 04 f 05 additionaly
Artem-spec/carsharing pull request #8
Opened 2021-10-18 05:32 UTC by Artem-spec

2021-10-18 15:13 UTC, EvgeniyaFilatova commented
- [x] Сделай так, чтобы дату "до" нельзя было выбрать раньше даты "от", а то сейчас если ее выбрать, то приложение вообще упадет с ошибкой
![изображение](https://user-images.githubusercontent.com/90593835/137759324-14884dec-c6a6-4788-ae74-8637eef70e96.png)

2021-10-18 15:18 UTC, EvgeniyaFilatova commented
- [x] Сбрасываются значения при переходе с шага "итого" на шаг "дополнительно", хотя ничего изменено не было
![изображение](https://user-images.githubusercontent.com/90593835/137759928-388407e5-c2dd-41bb-805e-d36cfe6c9218.png)
![изображение](https://user-images.githubusercontent.com/90593835/137760008-f25619a0-d8b5-493c-ba32-f2d3afb94b52.png)
![изображение](https://user-images.githubusercontent.com/90593835/137760142-f966e239-8012-409a-b5de-7388e410f210.png)

2021-10-18 15:44 UTC, EvgeniyaFilatova requested changes

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +    let cleanupFunction = false;
- [ ] А для чего здесь эта переменная? Во-первых, название не совсем правильное, нельзя писать Function, если в переменной не хранится функция. Во-вторых, будет ли у тебя эта переменная вообще когда-либо true? У тебя вроде useEffect этот будет срабатывать только один раз при инициализации компонента

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +  if (loading) {
- [ ] Лучше делать у компонента один return. Перепиши здесь так:
return (
loading && (section с лоадером)
!loading && (section с основным контентом)
)

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                let defaultCheck = true;
- [ ] Перепиши эту и нижнюю строчку компактнее с const, помня про автоматическое приведение типов

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                  `${rate.rateTypeId.name}, ${rate.price}`,
- [ ] Не забывай про деструктуризацию. Смотрю, у тебя много каких свойств берется из rate, и ты постоянно через точку обращаешься к свойствам

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                let defaultCheck = true;
- [ ] Тоже перепиши

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +    if (timeDiff < 0) {
- [ ] Смотрю у тебя сделана проверка на то, что я писала раньше. Но лучше сделать так, чтобы пользователь в принципе не мог выбрать дату, которую нельзя. Если что, то вот какие ошибки падают
![изображение](https://user-images.githubusercontent.com/90593835/137763415-7a48e695-80af-4738-bede-b4e451382ce1.png)

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +      switch (rate.rateTypeId.unit) {
Ты пошел по сложному пути) Проблема в том, что эти значения могут меняться хоть каждый день, потому что эту базу может редактировать любой (вы будете это делать во второй итерации). И соответственно тут может еще что-нибудь вылезти, чего в твоих Case нет. Но не переписывай это, просто к сведению, что в какой-то момент может что-то поломаться

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +            "date-input-active": dateFrom === "",
- [ ] Приведение типов, помни)

2021-10-18 15:44 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Servises/Servises.js
> +      setParam("Да");
- [ ] А зачем здесь передавать строку "да"? Вроде лучше булевое значение просто

2021-10-18 15:47 UTC, EvgeniyaFilatova commented
- [x] По структуре проекта: храни экшены и редьюсеры в папке store, чтобы все по редаксу было в одном месте
![изображение](https://user-images.githubusercontent.com/90593835/137765125-260d0018-8006-412f-87ba-1126d1b25434.png)

2021-10-19 18:37 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +    let cleanupFunction = false;
Я переименовал. Гуглил ошибку, то что useEffect  чистая функция. Обращение к серверу вызывало эту ошибку.
Вот как раз этот способ помогает разрешить ошибку. Как я понял это запрет использования обновления состояния при размонтировании компонента.

2021-10-19 18:48 UTC, Artem-spec commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +    if (timeDiff < 0) {
Исправлено

2021-10-20 06:50 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +  if (loading) {
Исправлено

2021-10-20 06:54 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                let defaultCheck = true;
Исправлено

2021-10-20 06:54 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                let defaultCheck = true;
Исправлено

2021-10-20 16:44 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                  `${rate.rateTypeId.name}, ${rate.price}`,
Здесь деструктуризация наверное не подойдет, мне же нужно собрать массив значений.   Для того, чтобы не использовать несколько компонентов, я использую один.  Где была возможность использовал spread.

2021-10-20 16:48 UTC, Artem-spec commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +            "date-input-active": dateFrom === "",
Исправлено, прошу прощения, очень частая моя ошибка. Переключаюсь каждый раз с одного синтаксиса на другой. Забываю

2021-10-21 11:43 UTC, Artem-spec commented on src/components/Reservation/Additionally/Servises/Servises.js
> +      setParam("Да");
Исправлено

2021-10-21 12:54 UTC, EvgeniyaFilatova requested changes

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                  const defaultCheck = color === order.color ? true : false;
- [ ] Для логических операций не используй тернарник, JS же сам тебе вернет true или false, то есть тут можно написать просто: const defaultCheck = color === order.color

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +          dateFrom.getHours() + 1,
- [ ] А зачем везде +1 к часу? Ты поэтому в new Date не передаешь просто dateFrom?

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +          dateFormat="MMMM d, yyyy hh:mm aa"
- [ ] В России обычно не используют обозначения до полудня или после полудня, лучше убрать "aa" для формата времени, чтобы было только часы и минуты

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                        setChecked={() => {}}
- [ ] Зачем тут пустая функция?

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                    order.rate.rateId === rate.id ? true : false;
- [ ] Тоже сделать без тернарника можно

2021-10-21 12:54 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> -      let calcPrice;
- [ ] Верни расчет цены в зависимости от тарифа (если это можно сейчас вернуть безболезненно), все-таки цена должны меняться в зависимости от тарифа. Тут просто немного неудобно сделано со стороны бэка, можно было чуть меньше заморачиваться и не парсить тут строку, но раз ты уже заморочился, то оставь такой расчет)

2021-10-21 15:01 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                  const defaultCheck = color === order.color ? true : false;
Исправлено

2021-10-21 15:01 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                    order.rate.rateId === rate.id ? true : false;
Исправлено

2021-10-21 15:12 UTC, Artem-spec commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +          dateFormat="MMMM d, yyyy hh:mm aa"
Исправлено

2021-10-21 15:49 UTC, Artem-spec commented on src/components/Reservation/Additionally/Additionally.js
> +                        setChecked={() => {}}
Исправлено

2021-10-21 16:03 UTC, Artem-spec commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> +          dateFrom.getHours() + 1,
В одном месте исправил, но в других + 1 необходимо чтобы сразу исключить ситуацию заказа на 0 часов. К тому же нужно задавать минимальное время. Если установить допустим dateFrom и dateTo один и тот же день, то всё равно datepicker установит время на заблокированное. Поэтому для dateTo беру дату и время dateFrom  и к часам + 1 .

2021-10-21 17:40 UTC, Artem-spec commented on src/components/Reservation/Additionally/DateInterval/DateInterval.js
> -      let calcPrice;
Исправлено

2021-10-22 05:36 UTC, EvgeniyaFilatova commented on src/components/Reservation/Additionally/Additionally.js
> +                        // setChecked={() => {}}
Лучше вообще удалить, а не просто закомментить

2021-10-23 14:50 UTC, merged